@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDM3MDYzYzY2YWJkNGI2ZTQxNThjNCIsInVzZXJuYW1lIjoidXNlclJlc3QiLCJpYXQiOjE3NDE5MTI3ODIsImV4cCI6MTc0MTkxMzY4Mn0._0i1NTcoVal45yTKhqneR-h6Yne3lSh_oOLxyrdTFog
@refresh=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDM3MDYzYzY2YWJkNGI2ZTQxNThjNCIsInVzZXJuYW1lIjoidXNlclJlc3QiLCJpYXQiOjE3NDE5MTI3NDN9.PfWrocLibuX402Ruw4wtT2moGpVjw0TJ_t5tR6nfn98
@user=userRest
@pass=rest123
//CADASTRO
POST http://localhost:5000/auth/register/
Content-Type: application/json

{
    "username": "{{user}}",
    "password": "{{pass}}"
}

###
//LOGIN
POST http://localhost:5000/auth/login/
Content-Type: application/json

{
    "username": "{{user}}",
    "password": "{{pass}}"
}

###
//ROTA PROTEGIDA HOME
GET http://localhost:5000/user/home
Authorization: Bearer {{token}}

###
//NOVO TOKEN
POST http://localhost:5000/auth/token
Content-Type: application/json

{
    "token": "{{refresh}}"
}

###
//LOGOUT
POST http://localhost:5000/auth/logout
Content-Type: application/json

{
    "token": "{{refresh}}"
}

###
//FILMES DO DB
GET http://localhost:5000/api/movies/popular

###
//RECOMENDAÇÕES
GET http://localhost:5000/api/recommendations/movies
Authorization: Bearer {{token}}
Content-Type: application/json

###

//AVALIAR FILME
POST http://localhost:5000/api/reviews/rate
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "movieId": 950396,
  "rating": 4
}